const EError = {
    ROUTING_ERROR: 1,
    NOT_FOUND: 2,
    DATABASE_ERROR: 3,
    INVALID_TYPE_ERROR: 4,
    UNAUTHORIZED: 5,
    FORBIDDEN: 6,
    NETWORK_ERROR: 7,
    TIMEOUT_ERROR: 8,
    FILE_NOT_FOUND: 9,
    VALIDATION_ERROR: 10,
    ACCESS_DENIED: 11,
    SERVER_ERROR: 12,
    SERVICE_UNAVAILABLE: 13
}

module.exports = {
    EError
}